spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ai_assistant?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}
    
  jpa:
    hibernate:
      ddl-auto: update
      
  ai:
    openai:
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      api-key: ${GEMINI_API_KEY}
      
cors:
  allowed-origins: http://localhost:3000,http://localhost

server:
  port: 8080
