spring:
  application:
    name: personal-productivity-assistant
  
  datasource:
    url: jdbc:mysql://localhost:3306/ai_assistant?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey_ThisShouldBeChangedInProduction_MakeItLongerForSecurity}
      expiration: 86400000
  
  ai:
    openai:
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      api-key: ${GEMINI_API_KEY:AIzaSyBQDyP6wMJ1C-FKb9QPl9MfOZmySS8lvgo}
      chat:
        options:
          model: gemini-2.5-flash
          temperature: 0.7
          max-tokens: 2000

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.productivity.assistant: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
